name: Commit lint

on:
  pull_request:
  push:
    branches: ['verify/**']

permissions:
  contents: read

jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      - run: npm install
      - name: Lint pull request commits
        run: npx commitlint --from ca1b02ce2eabe8252808b5256de3a92ccedd8e62 --to HEAD --verbose
